# Generated by Django 4.2.6 on 2024-03-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchSwipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitee',
            name='height',
        ),
        migrations.AddField(
            model_name='recruitee',
            name='allergy_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='biological_sex',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='consent_form_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='contact_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='current_medication_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='date_of_consent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='emergency_contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='family_medical_history_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='has_allergies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='has_family_medical_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='has_medical_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='has_medication_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='health_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='informed_consent_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='language_preferences',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='lifestyle_factors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='medical_history_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='medication_history_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='participation_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='personal_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='pregnancy_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='race',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='socioeconomic_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='study_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='taking_current_medications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recruitee',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitee',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
