# Generated by Django 4.2.6 on 2024-03-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchSwipe', '0002_remove_recruitee_height_recruitee_allergy_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitee',
            old_name='name',
            new_name='profession',
        ),
        migrations.RemoveField(
            model_name='recruitee',
            name='personal_id',
        ),
        migrations.RemoveField(
            model_name='recruitee',
            name='study_ids',
        ),
        migrations.AddField(
            model_name='recruitee',
            name='duration_of_participation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='hair_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='measurement_system',
            field=models.CharField(choices=[('imperial', 'Imperial'), ('metric', 'Metric')], default='metric', max_length=20),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='work_preference',
            field=models.CharField(blank=True, choices=[('group', 'Group'), ('solo', 'Solo'), ('no preference', 'No Preference')], max_length=50, null=True),
        ),
    ]
