# Generated by Django 4.2.6 on 2024-03-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchSwipe', '0003_rename_name_recruitee_profession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitee',
            name='consent_form_version',
        ),
        migrations.RemoveField(
            model_name='recruitee',
            name='date_of_consent',
        ),
        migrations.RemoveField(
            model_name='recruitee',
            name='informed_consent_status',
        ),
    ]
