# Generated by Django 4.2.6 on 2024-03-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchSwipe', '0005_remove_recruitee_race_recruitee_activity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitee',
            name='study_preference',
            field=models.CharField(blank=True, choices=[('cohort_study', 'Cohort study'), ('controlled_studies', 'Controlled studies'), ('cross_sectional_studies', 'Cross sectional studies'), ('systematic_review', 'Systematic review'), ('clinical_trials', 'Clinical trials'), ('experiment', 'Experiment'), ('case_series', 'Case series'), ('case_studies', 'Case studies'), ('correlation', 'Correlation'), ('interventional_studies', 'Interventional studies'), ('analytical_study', 'Analytical study'), ('research', 'Research'), ('design', 'Design'), ('descriptive_study', 'Descriptive study'), ('ecology', 'Ecology'), ('epidemiological_studies', 'Epidemiological studies'), ('preventive_healthcare', 'Preventive healthcare'), ('qualitative_research', 'Qualitative research'), ('randomized_controlled_trials', 'Randomized controlled trials'), ('observation', 'Observation'), ('genetic', 'Genetic'), ('references', 'References'), ('longitudinal_studies', 'Longitudinal studies')], max_length=100, null=True),
        ),
    ]
