# Generated by Django 4.2.6 on 2024-03-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchSwipe', '0006_recruitee_study_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitee',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='interest_1',
            field=models.CharField(blank=True, choices=[('basketball', 'Basketball'), ('football', 'Football'), ('volleyball', 'Volleyball'), ('marathon_running', 'Marathon running'), ('skiing', 'Skiing'), ('tennis', 'Tennis'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('baseball', 'Baseball'), ('mountain_climbing', 'Mountain climbing'), ('chess', 'Chess'), ('playing_a_musical_instrument', 'Playing a musical instrument'), ('reading', 'Reading'), ('writing', 'Writing'), ('sketching', 'Sketching'), ('photography', 'Photography'), ('design', 'Design'), ('blog_writing', 'Blog writing'), ('painting', 'Painting'), ('boardgames', 'Boardgames'), ('creating_and_organizing_a_book_club', 'Creating and organizing a book club'), ('networking_events', 'Networking events'), ('local_meetups', 'Local meetups'), ('volunteering_at_a_charity_center', 'Volunteering at a charity center'), ('public_speaking', 'Public speaking'), ('exploring_other_cultures', 'Exploring other cultures'), ('dancing', 'Dancing'), ('camping', 'Camping'), ('language_classes', 'Language classes'), ('archery', 'Archery'), ('gardening', 'Gardening'), ('stand_up_comedy', 'Stand-up comedy'), ('baking', 'Baking'), ('journaling', 'Journaling'), ('calligraphy', 'Calligraphy'), ('fencing', 'Fencing'), ('theater', 'Theater'), ('yoga', 'Yoga'), ('languages', 'Languages')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='interest_2',
            field=models.CharField(blank=True, choices=[('basketball', 'Basketball'), ('football', 'Football'), ('volleyball', 'Volleyball'), ('marathon_running', 'Marathon running'), ('skiing', 'Skiing'), ('tennis', 'Tennis'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('baseball', 'Baseball'), ('mountain_climbing', 'Mountain climbing'), ('chess', 'Chess'), ('playing_a_musical_instrument', 'Playing a musical instrument'), ('reading', 'Reading'), ('writing', 'Writing'), ('sketching', 'Sketching'), ('photography', 'Photography'), ('design', 'Design'), ('blog_writing', 'Blog writing'), ('painting', 'Painting'), ('boardgames', 'Boardgames'), ('creating_and_organizing_a_book_club', 'Creating and organizing a book club'), ('networking_events', 'Networking events'), ('local_meetups', 'Local meetups'), ('volunteering_at_a_charity_center', 'Volunteering at a charity center'), ('public_speaking', 'Public speaking'), ('exploring_other_cultures', 'Exploring other cultures'), ('dancing', 'Dancing'), ('camping', 'Camping'), ('language_classes', 'Language classes'), ('archery', 'Archery'), ('gardening', 'Gardening'), ('stand_up_comedy', 'Stand-up comedy'), ('baking', 'Baking'), ('journaling', 'Journaling'), ('calligraphy', 'Calligraphy'), ('fencing', 'Fencing'), ('theater', 'Theater'), ('yoga', 'Yoga'), ('languages', 'Languages')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='interest_3',
            field=models.CharField(blank=True, choices=[('basketball', 'Basketball'), ('football', 'Football'), ('volleyball', 'Volleyball'), ('marathon_running', 'Marathon running'), ('skiing', 'Skiing'), ('tennis', 'Tennis'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('baseball', 'Baseball'), ('mountain_climbing', 'Mountain climbing'), ('chess', 'Chess'), ('playing_a_musical_instrument', 'Playing a musical instrument'), ('reading', 'Reading'), ('writing', 'Writing'), ('sketching', 'Sketching'), ('photography', 'Photography'), ('design', 'Design'), ('blog_writing', 'Blog writing'), ('painting', 'Painting'), ('boardgames', 'Boardgames'), ('creating_and_organizing_a_book_club', 'Creating and organizing a book club'), ('networking_events', 'Networking events'), ('local_meetups', 'Local meetups'), ('volunteering_at_a_charity_center', 'Volunteering at a charity center'), ('public_speaking', 'Public speaking'), ('exploring_other_cultures', 'Exploring other cultures'), ('dancing', 'Dancing'), ('camping', 'Camping'), ('language_classes', 'Language classes'), ('archery', 'Archery'), ('gardening', 'Gardening'), ('stand_up_comedy', 'Stand-up comedy'), ('baking', 'Baking'), ('journaling', 'Journaling'), ('calligraphy', 'Calligraphy'), ('fencing', 'Fencing'), ('theater', 'Theater'), ('yoga', 'Yoga'), ('languages', 'Languages')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recruitee',
            name='interest_4',
            field=models.CharField(blank=True, choices=[('basketball', 'Basketball'), ('football', 'Football'), ('volleyball', 'Volleyball'), ('marathon_running', 'Marathon running'), ('skiing', 'Skiing'), ('tennis', 'Tennis'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('baseball', 'Baseball'), ('mountain_climbing', 'Mountain climbing'), ('chess', 'Chess'), ('playing_a_musical_instrument', 'Playing a musical instrument'), ('reading', 'Reading'), ('writing', 'Writing'), ('sketching', 'Sketching'), ('photography', 'Photography'), ('design', 'Design'), ('blog_writing', 'Blog writing'), ('painting', 'Painting'), ('boardgames', 'Boardgames'), ('creating_and_organizing_a_book_club', 'Creating and organizing a book club'), ('networking_events', 'Networking events'), ('local_meetups', 'Local meetups'), ('volunteering_at_a_charity_center', 'Volunteering at a charity center'), ('public_speaking', 'Public speaking'), ('exploring_other_cultures', 'Exploring other cultures'), ('dancing', 'Dancing'), ('camping', 'Camping'), ('language_classes', 'Language classes'), ('archery', 'Archery'), ('gardening', 'Gardening'), ('stand_up_comedy', 'Stand-up comedy'), ('baking', 'Baking'), ('journaling', 'Journaling'), ('calligraphy', 'Calligraphy'), ('fencing', 'Fencing'), ('theater', 'Theater'), ('yoga', 'Yoga'), ('languages', 'Languages')], max_length=50, null=True),
        ),
    ]
