# Generated by Django 4.2.11 on 2024-03-20 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchSwipe', '0008_alter_recruitee_ethnicity'),
        ('ResearchSwipe', '0008_alter_user_managers_alter_recruitee_ethnicity_and_more'),
    ]

    operations = [
    ]
