import pandas as pd

file_path = '/Users/mehdiamrani/Desktop/projectmoney/uni project/updated_recruiter.csv' 
volunteers_df = pd.read_csv(file_path)

study_titles =([
    "Exploring the Role of Robotics in Elderly Care",
    "Literary Depictions of Mental Health in Contemporary Fiction",
    "Advancements in Genetic Editing Technologies",
    "The Impact of Urban Green Spaces on Public Health",
    "Innovative Approaches to Addressing Homelessness",
    "Analyzing the Influence of Gaming on Cognitive Abilities",
    "Next-Generation Cancer Treatments: From Bench to Bedside",
    "The Intersection of Neuroscience and Architecture",
    "Promoting Eco-Friendly Practices in the Fashion Industry",
    "The Psychology of Conspiracy Beliefs and Misinformation",
    "Exploring Traditional Medicine Practices in Modern Healthcare",
    "Advancements in Quantum Computing Technologies",
    "Addressing Health Disparities in Underserved Communities",
    "Cultural Representations of Artificial Intelligence in Film",
    "The Role of Nutrition in Mental Health and Well-being",
    "Investigating the Impact of Climate Change on Wildlife Habitats",
    "Advancements in Sustainable Building Materials",
    "Exploring Indigenous Knowledge Systems in Environmental Conservation",
    "The Use of Blockchain Technology in Supply Chain Management",
    "Promoting Financial Literacy and Education",
    "The Influence of Parenting Styles on Child Development",
    "Advancements in Brain-Computer Interface Technology",
    "Exploring the Relationship Between Sleep and Mental Health",
    "The Role of Community Gardens in Urban Sustainability",
    "Innovative Approaches to STEM Education for Girls",
    "Analyzing the Impact of Social Determinants on Health Outcomes",
    "Exploring the Intersection of Religion and Medicine",
    "The Future of 3D Printing in Healthcare",
    "Promoting Cultural Diversity in Higher Education",
    "The Psychology of Creativity and Innovation",
    "Investigating the Impact of Air Pollution on Respiratory Health",
    "Advancements in Renewable Energy Policy and Implementation",
    "Exploring the Potential of Nanotechnology in Medicine",
    "The Intersection of Environmental Science and Social Justice",
    "Promoting Mental Health Support in the Workplace",
    "The Role of Storytelling in Science Communication",
    "Advancements in Sustainable Water Management",
    "Exploring the Impact of Artificial Light on Ecosystems",
    "Addressing Food Waste in the Hospitality Industry",
    "The Psychology of Happiness and Well-being",
    "Investigating the Effects of Mindfulness Practices on Stress Reduction",
    "The Role of Community-Based Tourism in Sustainable Development",
    "Exploring the Benefits of Nature-Based Therapies",
    "Advancements in Assistive Technologies for People with Disabilities",
    "Promoting Gender Equality in STEM Fields",
    "The Influence of Social Networks on Health Behaviors",
    "Exploring the Role of Architecture in Promoting Social Inclusion",
    "Advancements in Personalized Nutrition",
    "The Impact of Climate Change on Mental Health",
    "Investigating the Benefits of Music Therapy for Neurological Disorders"
])

study_descriptions = ([
    "Investigating how robotics can significantly improve the quality of life for elderly individuals by providing innovative solutions and advanced technologies. This study involves researching the development of assistive robots that can help with daily tasks, monitoring health metrics, and providing companionship to elderly individuals, ultimately aiming to enhance their independence and well-being.",
    "Analyzing intricate literary representations of mental health issues in contemporary fiction to gain deeper insights into the complex human psyche and societal perceptions. This research delves into novels, short stories, and other literary works to examine how authors portray mental illness, stigma, and treatment, offering valuable perspectives on societal attitudes and the subjective experience of mental health.",
    "Exploring the latest groundbreaking developments and ethical implications in gene-editing technologies, which hold immense promise for medical advancements and genetic therapies. This study involves reviewing recent advancements in CRISPR technology, gene therapy, and genome editing techniques, while also considering the ethical implications surrounding issues such as consent, equity, and unintended consequences.",
    "Examining how increased access to green spaces in densely populated urban areas positively impacts public health outcomes and fosters community well-being and environmental sustainability. This research involves analyzing urban planning initiatives, park design strategies, and community engagement efforts aimed at creating and preserving green spaces, with a focus on their role in promoting physical activity, mental health, and social cohesion.",
    "Exploring and devising innovative and holistic solutions to address the multifaceted challenges of homelessness and housing insecurity in modern societies. This study involves examining homelessness prevention programs, supportive housing models, and policies aimed at addressing the root causes of homelessness, including poverty, housing affordability, and systemic inequalities.",
    "Investigating the cognitive effects and societal impacts of immersive gaming experiences and virtual environments on individuals' behavior, cognition, and social interactions. This research involves conducting experiments and surveys to assess how virtual reality (VR) and augmented reality (AR) technologies influence cognitive functions, social behaviors, and emotional responses, with implications for gaming, education, therapy, and beyond.",
    "Discovering and disseminating the latest breakthroughs, cutting-edge therapies, and promising avenues of research in cancer treatment to improve patient outcomes and quality of life. This study involves reviewing clinical trials, experimental treatments, and emerging technologies in oncology, with a focus on personalized medicine, targeted therapies, and supportive care interventions to enhance the effectiveness of cancer treatment and patient well-being.",
    "Exploring how architectural design principles and urban planning strategies can positively influence mental states, emotional well-being, and overall quality of life. This research involves studying biophilic design, evidence-based design practices, and placemaking initiatives aimed at creating supportive environments that promote relaxation, creativity, and social connection, while also mitigating stress and enhancing resilience.",
    "Promoting sustainability, environmental consciousness, and social responsibility within the fashion industry by advocating for eco-friendly practices and ethical production methods. This study involves researching sustainable fashion initiatives, eco-friendly materials, and circular economy models, while also considering the social and environmental impacts of fast fashion and consumer behavior.",
    "Investigating the underlying psychological mechanisms and societal phenomena contributing to the proliferation of conspiracy beliefs and misinformation in contemporary culture. This research involves examining cognitive biases, social influence processes, and online echo chambers that contribute to the spread of conspiracy theories, while also exploring strategies for debunking misinformation and promoting critical thinking.",
    "Examining the integration and efficacy of traditional healing practices, alternative medicine, and holistic approaches within modern healthcare systems to enhance patient care and well-being. This study involves reviewing evidence-based research on complementary and integrative medicine modalities, such as acupuncture, herbal medicine, and mind-body therapies, while also considering their cultural significance, safety, and ethical considerations in healthcare delivery.",
    "Discovering the vast potential and transformative power of quantum computing to revolutionize industries, scientific research, and computational capabilities. This research involves studying quantum algorithms, quantum hardware developments, and applications in fields such as cryptography, optimization, and material science, while also addressing challenges related to scalability, error correction, and quantum supremacy.",
    "Addressing systemic disparities and inequities in healthcare access, delivery, and outcomes among marginalized populations through targeted interventions and policy reforms. This study involves examining healthcare disparities based on race, ethnicity, socioeconomic status, and geographic location, while also evaluating interventions such as community health centers, culturally competent care models, and policy initiatives aimed at reducing inequities and improving health equity.",
    "Analyzing depictions of artificial intelligence in popular culture, media representations, and public discourse to understand societal perceptions and ethical considerations. This research involves analyzing films, TV shows, and news articles to examine how AI is portrayed and perceived by the public, while also considering ethical dilemmas such as AI ethics, bias, and accountability.",
    "Exploring the intricate interplay between dietary patterns, nutritional choices, and mental health outcomes to inform holistic approaches to wellness and disease prevention. This study involves reviewing epidemiological studies, clinical trials, and meta-analyses on the relationship between nutrition and mental health, while also considering psychosocial factors, gut-brain interactions, and personalized dietary interventions.",
    "Investigating the far-reaching ecological consequences of climate change on global biodiversity, ecosystems, and environmental sustainability. This research involves studying climate change impacts on species distribution, ecosystem services, and natural resource management, while also examining adaptation strategies, conservation efforts, and policy responses aimed at mitigating environmental degradation and promoting resilience.",
    "Discovering innovative materials, construction techniques, and architectural designs that promote sustainability, energy efficiency, and environmental stewardship. This study involves researching green building practices, passive design strategies, and renewable energy integration in architecture, while also considering life cycle assessments, carbon footprint reduction, and green building certification standards.",
    "Exploring indigenous knowledge systems, cultural perspectives, and community-based approaches to environmental conservation, land stewardship, and sustainable development. This research involves collaborating with indigenous communities, local stakeholders, and traditional knowledge holders to document and integrate indigenous wisdom, practices, and values into conservation efforts, ecosystem management, and sustainable development projects.",
    "Investigating the diverse applications and potential disruptions of blockchain technology beyond cryptocurrencies, including supply chain management, governance, and data security. This study involves exploring blockchain platforms, smart contracts, and decentralized applications (DApps) in various sectors such as finance, healthcare, logistics, and governance, while also considering regulatory frameworks, interoperability challenges, and adoption barriers.",
    "Promoting financial literacy, economic empowerment, and equitable access to financial resources and opportunities for individuals and underserved communities. This research involves designing financial education programs, advocating for inclusive financial services, and supporting entrepreneurship and asset-building initiatives to address wealth disparities, promote economic mobility, and foster financial resilience.",
    "Analyzing the multifaceted influences of parenting styles, family dynamics, and socio-cultural factors on children's socio-emotional development and cognitive outcomes. This study involves longitudinal research, cross-cultural comparisons, and qualitative analyses to examine how parenting practices, family environments, and cultural values shape children's social, emotional, and cognitive development, with implications for parenting interventions and family support services.",
    "Discovering cutting-edge advancements and potential applications of brain-computer interface technology in healthcare, communication, and assistive technologies. This research involves studying neurotechnology innovations, brain-machine interfaces, and neural prosthetics for applications such as neurorehabilitation, neurofeedback, and communication augmentation, while also addressing ethical, privacy, and regulatory considerations.",
    "Investigating the bidirectional relationship between sleep patterns, sleep disorders, and mental health outcomes to develop holistic approaches to sleep hygiene and well-being. This study involves conducting sleep studies, clinical trials, and epidemiological research to explore the impact of sleep quality and quantity on mental health disorders such as depression, anxiety, and cognitive impairment, while also evaluating interventions such as cognitive-behavioral therapy for insomnia (CBT-I) and sleep hygiene education.",
    "Exploring the role of community gardens as sustainable urban interventions that foster community cohesion, food security, and environmental sustainability. This research involves participatory action research, community-based initiatives, and qualitative studies to examine how community gardens promote social interaction, healthy eating habits, and environmental stewardship, while also addressing issues such as food deserts, urban agriculture policies, and community resilience.",
    "Developing inclusive and empowering educational strategies and initiatives to engage and retain girls in STEM fields and bridge the gender gap in STEM professions. This study involves designing STEM outreach programs, mentorship initiatives, and curriculum reforms to address gender stereotypes, increase girls' interest and participation in STEM subjects, and support their career aspirations in STEM fields, while also advocating for systemic changes to promote gender equity in education and workforce development.",
    "Examining the complex interplay of social determinants, economic disparities, and healthcare access on health outcomes and healthcare disparities among diverse populations. This research involves analyzing population health data, health equity research, and health policy evaluations to understand how social and economic factors such as income inequality, racial discrimination, and neighborhood characteristics contribute to health disparities, while also identifying strategies to address systemic barriers and promote health equity for all.",
    "Exploring the intersections of spirituality, religious beliefs, and cultural practices with healthcare attitudes, treatment-seeking behaviors, and patient outcomes. This study involves qualitative research, patient surveys, and interdisciplinary collaborations to examine how spirituality and religion influence health beliefs, coping mechanisms, and healthcare decision-making, while also considering the role of healthcare providers in addressing patients' spiritual and cultural needs with respect and sensitivity.",
    "Discovering the latest advancements, innovative applications, and ethical considerations in 3D printing technologies for medical devices, prosthetics, and tissue engineering. This research involves studying bioprinting techniques, bioinks, and scaffold designs for regenerative medicine applications, while also considering regulatory frameworks, patient safety concerns, and equitable access to 3D printing technologies for personalized healthcare solutions.",
    "Promoting diversity, equity, and inclusion within educational institutions and fostering environments that celebrate cultural differences and perspectives. This study involves implementing diversity training programs, inclusive pedagogical practices, and student support services to create welcoming and supportive learning environments for students from diverse backgrounds, while also advocating for policies and institutional changes to address systemic barriers and promote educational equity.",
    "Investigating the cognitive processes, individual traits, and environmental factors that foster creativity, innovation, and problem-solving abilities. This research involves conducting cognitive psychology experiments, creativity assessments, and environmental scans to identify the cognitive, personality, and situational factors that influence creative thinking and problem-solving, while also exploring interventions to enhance creativity and foster innovation in individuals and organizations.",
    "Exploring the multifaceted health effects of air pollution, environmental toxins, and urban pollutants on respiratory health and overall well-being. This study involves epidemiological research, environmental monitoring, and exposure assessments to examine the health impacts of air pollution, including respiratory diseases, cardiovascular conditions, and mental health disorders, while also evaluating policy interventions and public health strategies to reduce environmental exposures and protect vulnerable populations.",
    "Examining policy frameworks, regulatory mechanisms, and public-private partnerships aimed at accelerating the adoption of renewable energy sources and mitigating climate change. This research involves policy analysis, stakeholder consultations, and case studies to assess the effectiveness of renewable energy policies, carbon pricing mechanisms, and international agreements in transitioning to a low-carbon economy and achieving climate mitigation goals, while also considering the role of technology innovation and market incentives in driving sustainable energy transitions.",
    "Discovering the transformative potential of nanotechnology in medicine, drug delivery systems, targeted therapies, and diagnostic tools for personalized healthcare. This study involves nanomaterial synthesis, biomedical applications, and preclinical studies to explore the unique properties of nanoscale materials for medical applications, including cancer treatment, drug delivery, imaging contrast agents, and point-of-care diagnostics, while also addressing safety concerns, regulatory considerations, and ethical implications.",
    "Exploring environmental justice movements, grassroots activism, and community-led initiatives aimed at addressing environmental inequalities and systemic injustices. This research involves participatory research methods, community organizing, and policy advocacy to support environmental justice campaigns, empower frontline communities, and advance policy reforms that promote equitable access to clean air, water, and land, while also addressing issues such as environmental racism and climate resilience.",
    "Promoting mental health awareness, destigmatizing mental illness, and fostering supportive, inclusive workplaces that prioritize employee well-being and psychological safety. This study involves workplace mental health assessments, stigma reduction interventions, and employee wellness programs to create psychologically safe and supportive work environments, while also providing resources and training to managers and employees to recognize and address mental health issues effectively.",
    "Investigating the narrative power of storytelling in science communication, public engagement, and knowledge dissemination across diverse audiences and stakeholders. This research involves narrative analysis, audience research, and communication strategies to explore how storytelling techniques can enhance public understanding of complex scientific concepts, foster empathy, and inspire action on issues such as climate change, public health, and technological innovation.",
    "Exploring sustainable water management practices, conservation strategies, and innovative technologies to address water scarcity, pollution, and resource depletion. This study involves hydrological modeling, water quality assessments, and policy analysis to evaluate water management practices such as rainwater harvesting, wastewater recycling, and ecosystem-based approaches to water conservation, while also considering social equity, governance structures, and stakeholder engagement in water resource management.",
    "Investigating the ecological impacts of artificial lighting, light pollution, and nighttime illumination on wildlife habitats, ecosystems, and biodiversity. This research involves field studies, remote sensing techniques, and ecological modeling to assess the effects of artificial light at night (ALAN) on wildlife behavior, reproduction, and ecosystem dynamics, while also exploring mitigation strategies such as light reduction measures, habitat restoration, and urban planning interventions to minimize ecological disruptions.",
    "Addressing food waste across the hospitality industry supply chain through sustainable practices, waste reduction strategies, and community partnerships. This study involves food waste audits, supply chain analysis, and consumer behavior research to identify opportunities for waste reduction, resource optimization, and circular economy initiatives in food service operations, while also promoting awareness campaigns and policy interventions to tackle food waste at local and global scales.",
    "Exploring evidence-based psychological theories, interventions, and positive psychology practices aimed at enhancing emotional well-being, resilience, and life satisfaction. This research involves meta-analyses, intervention studies, and longitudinal research to evaluate the effectiveness of positive psychology interventions such as gratitude exercises, mindfulness training, and strengths-based approaches in promoting psychological well-being and resilience across diverse populations, while also considering cultural adaptations and implementation strategies.",
    "Investigating the therapeutic benefits, neurobiological mechanisms, and clinical applications of mindfulness-based interventions for stress reduction and mental health promotion. This study involves clinical trials, neuroimaging studies, and psychophysiological assessments to examine how mindfulness practices such as meditation, yoga, and mindful breathing influence stress responses, emotional regulation, and neural plasticity, while also exploring their applications in clinical settings for treating anxiety, depression, and trauma-related disorders.",
    "Examining the social, economic, and environmental impacts of community-based tourism initiatives on local economies, cultural preservation, and sustainable development. This research involves case studies, stakeholder interviews, and economic analyses to assess the benefits and challenges of community-based tourism models, including community ecotourism cooperatives, homestay programs, and cultural heritage tourism, while also exploring strategies to enhance community participation, equitable benefit-sharing, and environmental conservation.",
    "Discovering the healing powers of nature-based therapies, ecotherapy interventions, and wilderness experiences for physical, emotional, and psychological well-being. This study involves ecotherapy programs, nature immersion retreats, and outdoor recreation therapy sessions to explore the restorative effects of nature on stress reduction, mood enhancement, and overall health and wellness, while also considering factors such as biophilia, environmental stewardship, and accessibility to green spaces for diverse populations.",
    "Exploring assistive technologies, adaptive devices, and inclusive design principles to enhance accessibility, autonomy, and quality of life for individuals with disabilities. This research involves user-centered design approaches, assistive technology assessments, and usability studies to develop and evaluate technologies such as prosthetics, mobility aids, and sensory devices that empower individuals with disabilities to participate fully in daily activities, social interactions, and community life, while also advocating for universal design standards and disability rights.",
    "Promoting gender equality, diversity, and inclusion in STEM fields through advocacy, mentorship programs, and policy reforms. This study involves analyzing gender disparities, bias in STEM education and workforce, and implementing interventions such as mentorship programs, gender-neutral recruitment practices, and inclusive policies to support women, underrepresented minorities, and LGBTQ+ individuals in pursuing STEM education and careers, while also addressing systemic barriers and cultural norms that perpetuate inequities.",
    "Examining the influence of social networks, peer interactions, and online communities on health-related behaviors, lifestyle choices, and public health outcomes. This research involves social network analysis, survey research, and qualitative interviews to explore how social relationships, peer support networks, and digital communities influence health behaviors such as smoking, physical activity, and diet, while also considering the role of social influence, social norms, and social support in shaping health outcomes and disparities.",
    "Exploring architectural design principles, urban planning strategies, and inclusive spaces that promote social inclusion, accessibility, and diversity. This study involves participatory design processes, universal design guidelines, and case studies of inclusive public spaces to examine how built environments can be designed to accommodate diverse needs, preferences, and identities, while also fostering social interaction, community engagement, and a sense of belonging for all individuals.",
    "Discovering personalized approaches to nutrition, dietary interventions, and dietary guidelines tailored to individual preferences, health goals, and nutritional needs. This research involves nutrigenomics, personalized nutrition assessments, and dietary tracking technologies to identify genetic, metabolic, and lifestyle factors that influence nutritional requirements and responses to dietary interventions, while also considering cultural variations, socioeconomic factors, and sustainability considerations in personalized nutrition recommendations.",
    "Investigating the psychological impacts of climate change, eco-anxiety, and environmental stressors on mental health, well-being, and resilience. This study involves surveys, qualitative interviews, and psychological assessments to explore how climate-related events, ecological disruptions, and environmental changes affect mental health outcomes such as anxiety, depression, and post-traumatic stress disorder (PTSD), while also examining coping mechanisms, community resilience, and interventions to promote psychological adaptation and climate action.",
    "Exploring the therapeutic applications, neurological mechanisms, and clinical efficacy of music therapy interventions for neurological disorders and cognitive impairments. This research involves clinical trials, neuroimaging studies, and music therapy sessions to investigate how music-based interventions such as rhythmic auditory stimulation, singing, and music listening influence brain function, motor skills, and cognitive abilities in individuals with conditions such as Parkinson's disease, stroke, dementia, and autism spectrum disorder, while also exploring personalized approaches and interdisciplinary collaborations to optimize therapeutic outcomes.",
])

study_descriptions_twitter =([
    "Investigating how robotics can improve the quality of life for elderly individuals.",
    "Analyzing literary representations of mental health issues in contemporary fiction.",
    "Exploring the latest developments in gene-editing technologies.",
    "Examining how access to green spaces in cities affects public health.",
    "Exploring innovative solutions to homelessness and housing insecurity.",
    "Investigating the cognitive effects of gaming and virtual environments.",
    "Discover the latest breakthroughs in cancer treatment research.",
    "Exploring how architecture can influence mental states and well-being.",
    "Promoting sustainability and ethical practices in the fashion industry.",
    "Investigating the psychological factors behind belief in conspiracy theories.",
    "Examining the integration of traditional healing practices into modern healthcare systems.",
    "Discover the potential of quantum computing to revolutionize various industries.",
    "Addressing disparities in healthcare access and outcomes among marginalized populations.",
    "Analyzing how AI is portrayed in popular culture and its implications.",
    "Exploring the connection between diet, nutrition, and mental health.",
    "Investigating the effects of climate change on biodiversity and ecosystems.",
    "Discover sustainable materials and construction techniques for a greener future.",
    "Exploring indigenous perspectives on environmental conservation and sustainability.",
    "Investigating the applications of blockchain technology beyond cryptocurrencies.",
    "Promoting financial literacy and empowerment for individuals and communities.",
    "Analyzing how parenting styles shape children's behavior and development.",
    "Discover the latest advancements in brain-computer interface technology.",
    "Investigating the bidirectional relationship between sleep patterns and mental health.",
    "Exploring the role of community gardens in promoting sustainable urban living.",
    "Developing innovative strategies to engage girls in STEM fields.",
    "Examining how social and economic factors influence health outcomes.",
    "Exploring the intersection of spirituality, religion, and healthcare practices.",
    "Discover the latest developments in 3D printing for medical applications.",
    "Promoting diversity and inclusivity in educational settings.",
    "Investigating the cognitive processes underlying creativity and innovation.",
    "Exploring the health effects of air pollution and strategies for mitigation.",
    "Examining policies and initiatives aimed at promoting renewable energy adoption.",
    "Discover the potential of nanotechnology for targeted drug delivery and diagnostics.",
    "Exploring environmental justice issues and community activism.",
    "Promoting mental health awareness and support within workplaces.",
    "Investigating the use of storytelling to communicate scientific concepts.",
    "Exploring sustainable approaches to water conservation and management.",
    "Investigating the ecological impacts of artificial lighting and potential solutions.",
    "Addressing challenges and implementing solutions to reduce food waste.",
    "Exploring psychological theories and practices aimed at enhancing well-being.",
    "Investigating the effectiveness of mindfulness-based interventions for stress relief.",
    "Examining the role of tourism in promoting sustainable development and cultural exchange.",
    "Discover the therapeutic benefits of connecting with nature.",
    "Exploring assistive technologies designed to enhance accessibility and independence.",
    "Promoting gender equity and diversity in science, technology, engineering, and mathematics.",
    "Examining how social networks influence health-related behaviors and outcomes.",
    "Exploring architectural design principles for creating inclusive environments.",
    "Discover personalized approaches to nutrition tailored to individual needs and preferences.",
    "Investigating the psychological impacts of climate change and strategies for resilience.",
    "Exploring the therapeutic benefits of music for neurological conditions and disorders."
])

print("Length of study_titles:", len(study_titles))
print("Length of study_descriptions:", len(study_descriptions))

print("Number of rows in volunteers_df:", len(volunteers_df))

studies_df = pd.DataFrame({
    "Recruiter": volunteers_df["Name"],
    "Title": study_titles * (len(volunteers_df) // len(study_titles)),
    
    "Description": study_descriptions * (len(volunteers_df) // len(study_descriptions)),
    "Description_twitter": study_descriptions_twitter * (len(volunteers_df) // len(study_descriptions_twitter))
})

studies_csv_path = "/Users/mehdiamrani/Desktop/projectmoney/uni project/clinical_research_studies_full.csv"
studies_df.to_csv(studies_csv_path, index=False)

print(f"CSV file saved: {studies_csv_path}")
