<<<<<<< HEAD
# Generated by Django 4.2.11 on 2024-03-20 17:13
=======
# Generated by Django 4.2.11 on 2024-03-20 16:37
>>>>>>> e3a4e16e2b7db7e599a9c082609381aeabbd0dd9

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('recruitee_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Accepted/Rejected status of the recruitee', max_length=8)),
                ('study_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Accepted/Rejected status of the study', max_length=8)),
            ],
        ),
    ]
