# Generated by Django 4.2.11 on 2024-03-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('recruitee_status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], default='rejected', help_text='Accepted/Rejected status of the recruitee', max_length=8)),
                ('study_status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], default='rejected', help_text='Accepted/Rejected status of the study', max_length=8)),
            ],
        ),
    ]
