<<<<<<< Updated upstream
# Generated by Django 4.2.11 on 2024-03-19 16:58
=======
# Generated by Django 4.2.11 on 2024-03-19 16:44
>>>>>>> Stashed changes

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< Updated upstream
        ('Syed', '0003_study_health_status_study_work_preference_and_more'),
        ('ResearchSwipe', '0008_alter_recruitee_ethnicity'),
=======
        ('ResearchSwipe', '0008_alter_recruitee_ethnicity'),
        ('Syed', '0003_study_health_status_study_work_preference_and_more'),
>>>>>>> Stashed changes
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< Updated upstream
            name='ProfileInteraction',
            fields=[
                ('match_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zstatus', models.BooleanField(default=False, help_text='True for accepted, False for rejected')),
=======
            name='Matches',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('recruitee_status', models.BooleanField(default=False, help_text='True for accepted, False for rejected')),
                ('study_status', models.BooleanField(default=False, help_text='True for accepted, False for rejected')),
>>>>>>> Stashed changes
                ('recruitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='ResearchSwipe.recruitee')),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='Syed.study')),
            ],
            options={
                'unique_together': {('study', 'recruitee')},
            },
        ),
    ]
