# Generated by Django 4.2.11 on 2024-03-20 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mo', '0001_initial'),
        ('ResearchSwipe', '0001_initial'),
        ('Syed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='recruitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitee_interactions', to='ResearchSwipe.recruitee'),
        ),
        migrations.AddField(
            model_name='matches',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_interactions', to='Syed.study'),
        ),
    ]
