# Generated by Django 4.2.11 on 2024-03-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileinteraction',
            old_name='zstatus',
            new_name='recruitee_status',
        ),
        migrations.AddField(
            model_name='profileinteraction',
            name='study_status',
            field=models.BooleanField(default=False, help_text='True for accepted, False for rejected'),
        ),
    ]
