# Generated by Django 4.2.11 on 2024-03-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinteraction',
            name='interaction_date',
        ),
    ]
