# Generated by Django 4.2.11 on 2024-03-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mo', '0002_remove_profileinteraction_interaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinteraction',
            name='status',
            field=models.BooleanField(default=False, help_text='True for accepted, False for rejected'),
        ),
    ]
