# Generated by Django 4.2.11 on 2024-03-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mo', '0002_rename_zstatus_profileinteraction_recruitee_status_and_more'),
    ]

    operations = [
    ]
