# Generated by Django 4.2.11 on 2024-03-18 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Syed', '0003_study_health_status_study_work_preference_and_more'),
        ('ResearchSwipe', '0008_alter_recruitee_ethnicity'),
        ('Mo', '0003_alter_profileinteraction_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profileinteraction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='profileinteraction',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='Syed.study'),
        ),
        migrations.AlterUniqueTogether(
            name='profileinteraction',
            unique_together={('study', 'recruitee')},
        ),
        migrations.RemoveField(
            model_name='profileinteraction',
            name='recruiter',
        ),
    ]
