# Generated by Django 4.2.11 on 2024-03-19 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Syed', '0003_study_health_status_study_work_preference_and_more'),
        ('ResearchSwipe', '0008_alter_recruitee_ethnicity'),
        ('Mo', '0003_auto_20240319_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinteraction',
            name='match_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profileinteraction',
            name='recruitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitee_interactions', to='ResearchSwipe.recruitee'),
        ),
        migrations.AlterField(
            model_name='profileinteraction',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_interactions', to='Syed.study'),
        ),
    ]
