# Generated by Django 4.2.11 on 2024-03-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchSwipe', '0008_alter_recruitee_ethnicity'),
        ('Syed', '0003_study_health_status_study_work_preference_and_more'),
        ('Mo', '0004_alter_profileinteraction_match_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileInteraction',
            new_name='Matches',
        ),
    ]
