# Generated by Django 4.2.11 on 2024-03-18 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Syed', '0003_study_health_status_study_work_preference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mo', '0004_alter_profileinteraction_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Syed.study')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('study', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='ProfileInteraction',
        ),
    ]
