# Generated by Django 4.2.11 on 2024-03-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mo', '0005_rename_profileinteraction_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='recruitee_status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', help_text='Accepted/Rejected/Pending status of the recruitee', max_length=8),
        ),
        migrations.AlterField(
            model_name='matches',
            name='study_status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', help_text='Accepted/Rejected/Pending status of the study', max_length=8),
        ),
    ]
