# Generated by Django 4.2.11 on 2024-03-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mo', '0006_profileinteraction_delete_studyapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinteraction',
            name='status',
        ),
        migrations.AddField(
            model_name='profileinteraction',
            name='recruitee_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileinteraction',
            name='study_status',
            field=models.BooleanField(default=False),
        ),
    ]
