# Generated by Django 4.2.11 on 2024-03-19 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ResearchSwipe', '0008_alter_recruitee_ethnicity'),
        ('Syed', '0003_study_health_status_study_work_preference_and_more'),
        ('Mo', '0007_remove_profileinteraction_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('recruitee_status', models.BooleanField(default=False, help_text='True for accepted, False for rejected')),
                ('study_status', models.BooleanField(default=False, help_text='True for accepted, False for rejected')),
                ('recruitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='ResearchSwipe.recruitee')),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='Syed.study')),
            ],
            options={
                'unique_together': {('study', 'recruitee')},
            },
        ),
        migrations.DeleteModel(
            name='ProfileInteraction',
        ),
    ]
