# Generated by Django 4.2.11 on 2024-03-20 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mo', '0006_alter_matches_recruitee_status_and_more'),
        ('Mo', '0010_rename_profileinteractions_matches'),
    ]

    operations = [
    ]
