#Data validation
NATIONALITY_CHOICES = [
    ('afghan', 'Afghan'),
    ('albanian', 'Albanian'),
    ('algerian', 'Algerian'),
    ('american', 'American'),
    ('andorran', 'Andorran'),
    ('angolan', 'Angolan'),
    ('anguillan', 'Anguillan'),
    ('antigua_and_barbuda', 'Citizen of Antigua and Barbuda'),
    ('argentine', 'Argentine'),
    ('armenian', 'Armenian'),
    ('australian', 'Australian'),
    ('austrian', 'Austrian'),
    ('azerbaijani', 'Azerbaijani'),
    ('bahamian', 'Bahamian'),
    ('bahraini', 'Bahraini'),
    ('bangladeshi', 'Bangladeshi'),
    ('barbadian', 'Barbadian'),
    ('belarusian', 'Belarusian'),
    ('belgian', 'Belgian'),
    ('belizean', 'Belizean'),
    ('beninese', 'Beninese'),
    ('bermudian', 'Bermudian'),
    ('bhutanese', 'Bhutanese'),
    ('bolivian', 'Bolivian'),
    ('bosnia_and_herzegovina', 'Citizen of Bosnia and Herzegovina'),
    ('botswanan', 'Botswanan'),
    ('brazilian', 'Brazilian'),
    ('british', 'British'),
    ('british_virgin_islander', 'British Virgin Islander'),
    ('bruneian', 'Bruneian'),
    ('bulgarian', 'Bulgarian'),
    ('burkinan', 'Burkinan'),
    ('burmese', 'Burmese'),
    ('burundian', 'Burundian'),
    ('cambodian', 'Cambodian'),
    ('cameroonian', 'Cameroonian'),
    ('canadian', 'Canadian'),
    ('cape_verdean', 'Cape Verdean'),
    ('cayman_islander', 'Cayman Islander'),
    ('central_african', 'Central African'),
    ('chadian', 'Chadian'),
    ('chilean', 'Chilean'),
    ('chinese', 'Chinese'),
    ('colombian', 'Colombian'),
    ('comoran', 'Comoran'),
    ('congolese_congo', 'Congolese (Congo)'),
    ('congolese_drc', 'Congolese (DRC)'),
    ('cook_islander', 'Cook Islander'),
    ('costa_rican', 'Costa Rican'),
    ('croatian', 'Croatian'),
    ('cuban', 'Cuban'),
    ('cymraes', 'Cymraes'),
    ('cymro', 'Cymro'),
    ('cypriot', 'Cypriot'),
    ('czech', 'Czech'),
    ('danish', 'Danish'),
    ('djiboutian', 'Djiboutian'),
    ('dominican', 'Dominican'),
    ('dominican_republic', 'Citizen of the Dominican Republic'),
    ('dutch', 'Dutch'),
    ('east_timorese', 'East Timorese'),
    ('ecuadorean', 'Ecuadorean'),
    ('egyptian', 'Egyptian'),
    ('emirati', 'Emirati'),
    ('english', 'English'),
    ('equatorial_guinean', 'Equatorial Guinean'),
    ('eritrean', 'Eritrean'),
    ('estonian', 'Estonian'),
    ('ethiopian', 'Ethiopian'),
    ('faroese', 'Faroese'),
    ('fijian', 'Fijian'),
    ('filipino', 'Filipino'),
    ('finnish', 'Finnish'),
    ('french', 'French'),
    ('gabonese', 'Gabonese'),
    ('gambian', 'Gambian'),
    ('georgian', 'Georgian'),
    ('german', 'German'),
    ('ghanaian', 'Ghanaian'),
    ('gibraltarian', 'Gibraltarian'),
    ('greek', 'Greek'),
    ('greenlandic', 'Greenlandic'),
    ('grenadian', 'Grenadian'),
    ('guamanian', 'Guamanian'),
    ('guatemalan', 'Guatemalan'),
    ('guinea_bissau_citizen', 'Citizen of Guinea-Bissau'),
    ('guinean', 'Guinean'),
    ('guyanese', 'Guyanese'),
    ('haitian', 'Haitian'),
    ('honduran', 'Honduran'),
    ('hong_konger', 'Hong Konger'),
    ('hungarian', 'Hungarian'),
    ('icelandic', 'Icelandic'),
    ('indian', 'Indian'),
    ('indonesian', 'Indonesian'),
    ('iranian', 'Iranian'),
    ('iraqi', 'Iraqi'),
    ('irish', 'Irish'),
    ('israeli', 'Israeli'),
    ('italian', 'Italian'),
    ('ivorian', 'Ivorian'),
    ('jamaican', 'Jamaican'),
    ('japanese', 'Japanese'),
    ('jordanian', 'Jordanian'),
    ('kazakh', 'Kazakh'),
    ('kenyan', 'Kenyan'),
    ('kittitian', 'Kittitian'),
    ('kiribati', 'Citizen of Kiribati'),
    ('kosovan', 'Kosovan'),
    ('kuwaiti', 'Kuwaiti'),
    ('kyrgyz', 'Kyrgyz'),
    ('lao', 'Lao'),
    ('latvian', 'Latvian'),
    ('lebanese', 'Lebanese'),
    ('liberian', 'Liberian'),
    ('libyan', 'Libyan'),
    ('liechtenstein', 'Liechtenstein citizen'),
    ('lithuanian', 'Lithuanian'),
    ('luxembourger', 'Luxembourger'),
    ('macanese', 'Macanese'),
    ('macedonian', 'Macedonian'),
    ('malagasy', 'Malagasy'),
    ('malawian', 'Malawian'),
    ('malaysian', 'Malaysian'),
    ('maldivian', 'Maldivian'),
    ('malian', 'Malian'),
    ('maltese', 'Maltese'),
    ('marshallese', 'Marshallese'),
    ('martiniquais', 'Martiniquais'),
    ('mauritanian', 'Mauritanian'),
    ('mauritian', 'Mauritian'),
    ('mexican', 'Mexican'),
    ('micronesian', 'Micronesian'),
    ('moldovan', 'Moldovan'),
    ('monegasque', 'Monegasque'),
    ('mongolian', 'Mongolian'),
    ('montenegrin', 'Montenegrin'),
    ('montserratian', 'Montserratian'),
    ('moroccan', 'Moroccan'),
    ('mosotho', 'Mosotho'),
    ('mozambican', 'Mozambican'),
    ('namibian', 'Namibian'),
    ('nauruan', 'Nauruan'),
    ('nepalese', 'Nepalese'),
    ('new_zealander', 'New Zealander'),
    ('nicaraguan', 'Nicaraguan'),
    ('nigerian', 'Nigerian'),
    ('nigerien', 'Nigerien'),
    ('niuean', 'Niuean'),
    ('north_korean', 'North Korean'),
    ('northern_irish', 'Northern Irish'),
    ('norwegian', 'Norwegian'),
    ('omani', 'Omani'),
    ('pakistani', 'Pakistani'),
    ('palauan', 'Palauan'),
    ('palestinian', 'Palestinian'),
    ('panamanian', 'Panamanian'),
    ('papua_new_guinean', 'Papua New Guinean'),
    ('paraguayan', 'Paraguayan'),
    ('peruvian', 'Peruvian'),
    ('pitcairn_islander', 'Pitcairn Islander'),
    ('polish', 'Polish'),
    ('portuguese', 'Portuguese'),
    ('prydeinig', 'Prydeinig'),
    ('puerto_rican', 'Puerto Rican'),
    ('qatari', 'Qatari'),
    ('romanian', 'Romanian'),
    ('russian', 'Russian'),
    ('rwandan', 'Rwandan'),
    ('salvadorean', 'Salvadorean'),
    ('sammarinese', 'Sammarinese'),
    ('samoan', 'Samoan'),
    ('sao_tomean', 'Sao Tomean'),
    ('saudi_arabian', 'Saudi Arabian'),
    ('scottish', 'Scottish'),
    ('senegalese', 'Senegalese'),
    ('serbian', 'Serbian'),
    ('seychelles_citizen', 'Citizen ofSeychelles', 'Citizen of Seychelles'),
    ('sierra_leonean', 'Sierra Leonean'),
    ('singaporean', 'Singaporean'),
    ('slovak', 'Slovak'),
    ('slovenian', 'Slovenian'),
    ('solomon_islander', 'Solomon Islander'),
    ('somali', 'Somali'),
    ('south_african', 'South African'),
    ('south_korean', 'South Korean'),
    ('south_sudanese', 'South Sudanese'),
    ('spanish', 'Spanish'),
    ('sri_lankan', 'Sri Lankan'),
    ('st_helenian', 'St Helenian'),
    ('st_lucian', 'St Lucian'),
    ('stateless', 'Stateless'),
    ('sudanese', 'Sudanese'),
    ('surinamese', 'Surinamese'),
    ('swazi', 'Swazi'),
    ('swedish', 'Swedish'),
    ('swiss', 'Swiss'),
    ('syrian', 'Syrian'),
    ('taiwanese', 'Taiwanese'),
    ('tajik', 'Tajik'),
    ('tanzanian', 'Tanzanian'),
    ('thai', 'Thai'),
    ('togolese', 'Togolese'),
    ('tongan', 'Tongan'),
    ('trinidadian', 'Trinidadian'),
    ('tristanian', 'Tristanian'),
    ('tunisian', 'Tunisian'),
    ('turkish', 'Turkish'),
    ('turkmen', 'Turkmen'),
    ('turks_and_caicos_islander', 'Turks and Caicos Islander'),
    ('tuvaluan', 'Tuvaluan'),
    ('ugandan', 'Ugandan'),
    ('ukrainian', 'Ukrainian'),
    ('uruguayan', 'Uruguayan'),
    ('uzbek', 'Uzbek'),
    ('vatican_citizen', 'Vatican citizen'),
    ('vanuatu', 'Citizen of Vanuatu'),
    ('venezuelan', 'Venezuelan'),
    ('vietnamese', 'Vietnamese'),
    ('vincentian', 'Vincentian'),
    ('wallisian', 'Wallisian'),
    ('welsh', 'Welsh'),
    ('yemeni', 'Yemeni'),
    ('zambian', 'Zambian'),
    ('zimbabwean', 'Zimbabwean')
    ]

ETHNICITY_CHOICES = [
        ('asian', 'Asian or Asian British'),
        ('indian', 'Indian'),
        ('pakistani', 'Pakistani'),
        ('bangladeshi', 'Bangladeshi'),
        ('chinese', 'Chinese'),
        ('other_asian', 'Any other Asian background'),
        ('black', 'Black, Black British, Caribbean or African'),
        ('caribbean', 'Caribbean'),
        ('african', 'African'),
        ('other_black', 'Any other Black, Black British, or Caribbean background'),
        ('mixed', 'Mixed or multiple ethnic groups'),
        ('white_black_caribbean', 'White and Black Caribbean'),
        ('white_black_african', 'White and Black African'),
        ('white_asian', 'White and Asian'),
        ('other_mixed', 'Any other Mixed or multiple ethnic background'),
        ('white', 'White'),
        ('british', 'English, Welsh, Scottish, Northern Irish or British'),
        ('irish', 'Irish'),
        ('gypsy_irish_traveller', 'Gypsy or Irish Traveller'),
        ('roma', 'Roma'),
        ('other_white', 'Any other White background'),
        ('other', 'Other ethnic group'),
        ('arab', 'Arab'),
        ('any_other', 'Any other ethnic group'),
    ]

ACTIVITY_LEVEL_CHOICES = [
        ('sedentary', 'Sedentary'),
        ('light', 'Light Activity'),
        ('moderate', 'Moderate Activity'),
        ('active', 'Active'),
    ]

HAIR_COLOR_CHOICES = [
        ('black', 'Black'),
        ('brown', 'Brown'),
        ('blonde', 'Blonde'),
        ('ginger', 'Ginger'),
        ('gray', 'Gray'),
        ('white', 'White'),
    ]

SOCIOECONOMIC_STATUS_CHOICES = [
        ('low', 'Low'),
        ('middle', 'Middle'),
        ('high', 'High'),
    ]

HEALTH_STATUS_CHOICES = [
        ('good', 'Good'),
        ('fair', 'Fair'),
        ('poor', 'Poor'),
    ]

MEASUREMENT_CHOICES = [
    ('imperial', 'Imperial'), 
    ('metric', 'Metric'),
]

GROUP_CHOICES = [
    ('group', 'Group'), 
    ('solo', 'Solo'), 
    ('no preference', 'No Preference'),
]
#End of data validation