# Generated by Django 4.2.6 on 2024-03-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Syed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='race',
        ),
    ]
